# Site settings
author: Raul A Figueroa
title: Blog
header-img: img/home-bg.png
email: raul.a.figueroa@hotmail.com
copyright_name: Raul A Figueroa
description: > # this means to ignore newlines until "baseurl:"
  Blogged on topics I have to stumble upon.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FigueroaR

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
